#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-dm-do-adapter
Version  : 1.2.0
Release  : 4
URL      : https://rubygems.org/downloads/dm-do-adapter-1.2.0.gem
Source0  : https://rubygems.org/downloads/dm-do-adapter-1.2.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-dm-core
BuildRequires : rubygem-jeweler
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec

%description
= dm-do-adapter
A DataObjects Adapter for DataMapper

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n dm-do-adapter-1.2.0
gem spec %{SOURCE0} -l --ruby > rubygem-dm-do-adapter.gemspec

%build
gem build rubygem-dm-do-adapter.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
dm-do-adapter-1.2.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/dm-do-adapter-1.2.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/dm-do-adapter-1.2.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/dm-do-adapter-1.2.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/dm-do-adapter-1.2.0/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/dm-do-adapter-1.2.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/dm-do-adapter-1.2.0/VERSION
/usr/lib64/ruby/gems/2.3.0/gems/dm-do-adapter-1.2.0/dm-do-adapter.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/spec/shared_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/dm-do-adapter-1.2.0/tasks/yard.rake
/usr/lib64/ruby/gems/2.3.0/gems/dm-do-adapter-1.2.0/tasks/yardstick.rake
/usr/lib64/ruby/gems/2.3.0/specifications/dm-do-adapter-1.2.0.gemspec
